version: "2"
services:
  app:
    image: glechner99/flask-app
    container_name: flask-app-container
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    labels:
      kompose.service.type: LoadBalancer

  db:
    image: mysql:5.7
    container_name: flask-app-db-container
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    labels:
      kompose.service.type: LoadBalancer
